### ISSUE TITLE
Q4 2020 / Q1 2021 roadmap

### ISSUE THREAD

**Issue by land47** [land47/router#2]
**Фичи:**
- [x] Навигация
- [x] Управление навигацией системными кнопками назад / вперёд
- [x] Параметры текущей записи в навигации
- [x] Обработка ссылок вида vk.com/app000#panel=info
- [x] iOS Swipeback
- [x] Управление модальными окнами
- [x] Управление попаутами
- [x] Управление снэкбарами
- [x] Передача состояния в ``useStructure``
- [x] Кэширование
- [x] Обработка асинхронных параметров

**Баги:**
- [x] Первый рендер приложения происходит два раза
- [x] Ломается навигация при быстром переходе на другое состояние

**Comment by evtn** [comment]
как создать мини-приложение

**Comment by ItzNeviKat** [comment]
где снэкбары не вижу
